name: Build and Push Docker Image

on:
  push:
    branches:
      - feat/docker
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, testnet, alpha]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: |
          touch .env
          echo "NEXT_PUBLIC_WEB3AUTH_NETWORK=${{ vars.NEXT_PUBLIC_WEB3AUTH_NETWORK }}" >> .env
          echo "NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_RPC_TARGET=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_RPC_TARGET }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_CHAIN_NAMESPACE=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_CHAIN_NAMESPACE }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_DISPLAY_NAME=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_DISPLAY_NAME }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_CHAIN_ID=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_CHAIN_ID }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_ADDRESS_PREFIX=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_ADDRESS_PREFIX }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_DENOM=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_DENOM }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_URL_SCHEME=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_URL_SCHEME }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_URL_DOMAIN=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_URL_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_GAS_PRICE=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_GAS_PRICE }}" >> .env
          echo "NEXT_PUBLIC_GHOSTCLOUD_GAS_LIMIT_MULTIPLIER=${{ vars.NEXT_PUBLIC_GHOSTCLOUD_GAS_LIMIT_MULTIPLIER }}" >> .env

      - name: Build and push with github release tag
        if: matrix.environment == 'alpha' && startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jgriffin555/ghostcloud-frontend:${{ env.GITHUB_REF_NAME }}

      - name: Build and push with environment tag for latest images
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jgriffin555/ghostcloud-frontend:${{ matrix.environment }}
